[
  {
    "name":"nginx",
    "essential":true,
    "hostname":"nginx.srv",
    "image":"DCKIMG_NGINX_NAME:DCKIMG_NGINX_TAG",
    "cpu":16,
    "memory":16,
    "memoryReservation":16,
    "ulimits":null,
    "environment":[
      {
        "name":"SERVICE",
        "value":"NGINX"
      }
    ],
    "readonlyRootFilesystem":null,
    "mountPoints":[

    ],
    "volumesFrom":[
      {
        "sourceContainer":"app-code",
        "readOnly":null
      }
    ],
    "disableNetworking":null,
    "portMappings":[
      {
        "hostPort": 0,
        "containerPort": 80,
        "protocol": "tcp"
      }
    ],
    "links":[
      "php-fpm"
    ],
    "dnsServers":[
      "8.8.8.8",
      "8.8.4.4"
    ],
    "dnsSearchDomains":[
      "search.dns.local"
    ],
    "extraHosts":[
      {
        "hostname":"extrahost.local",
        "ipAddress":"192.168.254.254"
      }
    ],
    "privileged":null,
    "dockerSecurityOptions":null,
    "user":null,
    "command":[

    ],
    "entryPoint":[
      "/bin/sh"
    ],
    "workingDirectory":"/var/www/html",
    "logConfiguration":{
      "logDriver":"awslogs",
      "options":{
        "awslogs-group":"dockerlogs",
        "awslogs-region":"eu-central-1",
        "awslogs-stream-prefix":"nginx"
      }
    },
    "dockerLabels":{
      "mysrv":"nginx",
      "myenv":"staging"
    }
  },
  {
    "name":"php-fpm",
    "essential":true,
    "hostname":"php-fpm.srv",
    "image":"DCKIMG_PHPFPM_NAME:DCKIMG_PHPFPM_TAG",
    "cpu":32,
    "memory":32,
    "memoryReservation":32,
    "ulimits":null,
    "environment":[
      {
        "name":"SERVICE",
        "value":"PHP-FPM"
      }
    ],
    "readonlyRootFilesystem":null,
    "mountPoints":[

    ],
    "volumesFrom":[
      {
        "sourceContainer":"app-code",
        "readOnly":null
      }
    ],
    "disableNetworking":null,
    "portMappings":[
      {
        "hostPort": 0,
        "containerPort": 9000,
        "protocol": "tcp"
      }
    ],
    "links":[

    ],
    "dnsServers":[
      "8.8.8.8",
      "8.8.4.4"
    ],
    "dnsSearchDomains":[
      "search.dns.local"
    ],
    "extraHosts":[
      {
        "hostname":"extrahost.local",
        "ipAddress":"192.168.254.254"
      }
    ],
    "privileged":null,
    "dockerSecurityOptions":null,
    "user":null,
    "command":[

    ],
    "entryPoint":[
      "/bin/sh"
    ],
    "workingDirectory":"/var/www/html",
    "logConfiguration":{
      "logDriver":"awslogs",
      "options":{
        "awslogs-group":"dockerlogs",
        "awslogs-region":"eu-central-1",
        "awslogs-stream-prefix":"phpfpm"
      }
    },
    "dockerLabels":{
      "mysrv":"php-fpm",
      "myenv":"staging"
    }
  },
  {
    "name":"magento-code",
    "essential":true,
    "hostname":"app-code.srv",
    "image":"DCKIMG_APPCODE_NAME:DCKIMG_APPCODE_TAG",
    "environment":[
      {
        "name":"SERVICE",
        "value":"APP-CODE"
      }
    ],
    "readonlyRootFilesystem":null,
    "mountPoints":[
      {
        "sourceVolume": "/var/www/html",
        "containerPath": "/var/www/html",
        "readOnly": false
      }
    ],
    "volumesFrom":[

    ],
    "disableNetworking":null,
    "portMappings":[

    ],
    "links":[

    ],
    "dnsServers":[
      "8.8.8.8",
      "8.8.4.4"
    ],
    "dnsSearchDomains":[
      "search.dns.local"
    ],
    "extraHosts":[
      {
        "hostname":"extrahost.local",
        "ipAddress":"192.168.254.254"
      }
    ],
    "privileged":null,
    "dockerSecurityOptions":null,
    "user":null,
    "command":[

    ],
    "entryPoint":[
      "/bin/sh"
    ],
    "workingDirectory":"/var/www/html",
    "logConfiguration":{
      "logDriver":"awslogs",
      "options":{
        "awslogs-group":"dockerlogs",
        "awslogs-region":"eu-central-1",
        "awslogs-stream-prefix":"appcode"
      }
    },
    "dockerLabels":{
      "mysrv":"app-code",
      "myenv":"staging"
    }
  }
]
